-- Add is_auto_generated column to invoices table
-- This indicates whether the invoice was automatically generated or manually created

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS is_auto_generated boolean DEFAULT true;

-- Add comment to document the column purpose
COMMENT ON COLUMN invoices.is_auto_generated IS 'Indicates if this invoice was automatically generated by the system'; 